config:
  storages:
    - x1: 10
      y1: 20
      z1: 30
      x2: 40
      y2: 50
      z2: 60
      world: "world"
    - x1: 15
      y1: 25
      z1: 35
      x2: 45
      y2: 55
      z2: 65
      world: "world"
      # Configure your storages here.
  sql:
    username: "root"
    password: "password"
    ip: "127.0.0.1"
    port: 3306
    database: "openid"
    # Configure your SQL settings here.