storages:
  region1:
    x1: 10
    y1: 20
    z1: 30
    x2: 40
    y2: 50
    z2: 60
    world: world
  region2:
    x1: 100
    y1: 120
    z1: 130
    x2: 140
    y2: 150
    z2: 160
    world: world
      # Configure your storages here.
sql:
  username: "root"
  password: "password"
  ip: "127.0.0.1"
  port: 3306
  database: "openid"
  # Configure your SQL settings here.